PSX_STOCKS = [
    ("RMPL",     "Rafhan Maize Products Co. Limited",                                      "FOOD & PERSONAL CARE PRODUCTS"),
    ("DLL",      "Dawood Lawrencepur Limited",                                             "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("HAFL",     "Hafiz Limited",                                                          "TEXTILE COMPOSITE"),
    ("PRET",     "Premium Textile Mills Limited",                                          "TEXTILE SPINNING"),
    ("BHAT",     "Bhanero Textile Mills Limited",                                          "TEXTILE COMPOSITE"),
    ("WAFI",     "Wafi Energy Pakistan Limited",                                           "OIL & GAS MARKETING COMPANIES"),
    ("SML",      "Shakarganj Limited",                                                     "SUGAR & ALLIED INDUSTRIES"),
    ("NSRM",     "The National Silk & Rayon Mills Limited",                                "SYNTHETIC & RAYON"),
    ("SAPT",     "Sapphire Textile Mills Limited",                                         "TEXTILE COMPOSITE"),
    ("JDWS",     "JDW Sugar Mills Limited",                                                "SUGAR & ALLIED INDUSTRIES"),
    ("GLPL",     "Gillette Pakistan Limited",                                              "FOOD & PERSONAL CARE PRODUCTS"),
    ("GADT",     "Gadoon Textile Mills Limited",                                           "TEXTILE SPINNING"),
    ("NML",      "Nishat Mills Limited",                                                   "TEXTILE COMPOSITE"),
    ("BAFS",     "Baba Farid Sugar Mills Limited",                                         "SUGAR & ALLIED INDUSTRIES"),
    ("UBL",      "United Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("DMC",      "D.M. Corporation Limited.",                                              "TEXTILE SPINNING"),
    ("AGLNCPS",  "Agritech Non-Voting (Pref) Class A",                                     "CHEMICAL"),
    ("NCPL",     "Nishat Chunian Power Limited",                                           "POWER GENERATION & DISTRIBUTION"),
    ("TRIPF",    "Tri-Pack Films Limited",                                                 "MISCELLANEOUS"),
    ("SHSML",    "Shahmurad Sugar Mills Limited",                                          "SUGAR & ALLIED INDUSTRIES"),
    ("JSGCL",    "JS Global Capital Limited",                                              "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("CHCC",     "Cherat Cement Company Limited",                                          "CEMENT"),
    ("LUCK",     "Lucky Cement Limited",                                                   "CEMENT"),
    ("FIMM",     "First Imrooz Modaraba",                                                  "MODARABAS"),
    ("NBP",      "National Bank of Pakistan",                                              "COMMERCIAL BANKS"),
    ("MUGHAL",   "Mughal Iron & Steel Industries Limited",                                 "ENGINEERING"),
    ("SASML",    "Sindh Abadgar's Sugar Mills Limited",                                    "SUGAR & ALLIED INDUSTRIES"),
    ("AGIL",     "Agriautos Industries Limited",                                           "AUTOMOBILE PARTS & ACCESSORIES"),
    ("PIOC",     "Pioneer Cement Limited",                                                 "CEMENT"),
    ("FIL",      "Fateh Industries Limited",                                               "LEATHER & TANNERIES"),
    ("BATA",     "Bata Pakistan Limited",                                                  "LEATHER & TANNERIES"),
    ("FASM",     "Faisal Spinning Mills Limited",                                          "TEXTILE COMPOSITE"),
    ("FCIBL",    "First Credit & Investment Bank Limited",                                 "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("SUHJ",     "Suhail Jute Mills Limited",                                              "JUTE"),
    ("JDMT",     "Janana De Malucho Textile Mills Limited",                                "TEXTILE SPINNING"),
    ("TOWL",     "Towellers Limited",                                                      "TEXTILE COMPOSITE"),
    ("NRL",      "National Refinery Limited",                                              "REFINERY"),
    ("SGPL",     "S. G. Power Limited",                                                    "POWER GENERATION & DISTRIBUTION"),
    ("SUTM",     "Sunrays Textile Mills Limited",                                          "TEXTILE SPINNING"),
    ("PPP",      "Pakistan Paper Products Limited",                                        "PAPER, BOARD & PACKAGING"),
    ("DGKC",     "D. G. Khan Cement Company Limited",                                      "CEMENT"),
    ("MCBIM",    "MCB Investment Management Limited",                                      "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("FZCM",     "Fazal Cloth Mills Limited",                                              "TEXTILE COMPOSITE"),
    ("SHJS",     "Shahtaj Sugar Mills Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("ZUMA",     "Zuma Resources Limited",                                                 "nan"),
    ("JSML",     "Jauharabad Sugar Mills Limited",                                         "SUGAR & ALLIED INDUSTRIES"),
    ("SYS",      "Systems Limited",                                                        "TECHNOLOGY & COMMUNICATION"),
    ("SEL",      "Sitara Energy Limited",                                                  "POWER GENERATION & DISTRIBUTION"),
    ("MLCF",     "Maple Leaf Cement Factory Limited",                                      "CEMENT"),
    ("HBL",      "Habib Bank Limited",                                                     "COMMERCIAL BANKS"),
    ("ENGROH",   "Engro Holdings Limited",                                                 "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ISL",      "International Steels Limited",                                           "ENGINEERING"),
    ("BWHL",     "Baluchistan Wheels Limited",                                             "AUTOMOBILE PARTS & ACCESSORIES"),
    ("MUGHALC",  "Mughal Iron & Steel Industries Ltd©",                                    "ENGINEERING"),
    ("SITC",     "Sitara Chemical Industries Limited",                                     "CHEMICAL"),
    ("PPL",      "Pakistan Petroleum Limited",                                             "OIL & GAS EXPLORATION COMPANIES"),
    ("UDPL",     "United Distributors Pakistan Limited",                                   "MISCELLANEOUS"),
    ("CWSM",     "Chakwal Spinning Mills Limited",                                         "TEXTILE SPINNING"),
    ("TGL",      "Tariq Glass Industries Limited",                                         "GLASS & CERAMICS"),
    ("THALL",    "Thal Limited",                                                           "AUTOMOBILE PARTS & ACCESSORIES"),
    ("GATI",     "Gatron (Industries) Limited",                                            "SYNTHETIC & RAYON"),
    ("ABOT",     "Abbott Laboratories (Pakistan) Limited",                                 "PHARMACEUTICALS"),
    ("BCL",      "Bolan Castings Limited",                                                 "ENGINEERING"),
    ("QUICE",    "Quice Food Industries Limited",                                          "FOOD & PERSONAL CARE PRODUCTS"),
    ("PIAHCLA",  "PIA Holding Company Limited",                                            "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("AKDHL",    "AKD Hospitality Limited ",                                               "MISCELLANEOUS"),
    ("SINDM",    "Sindh Modaraba",                                                         "MODARABAS"),
    ("AHL",      "Arif Habib Limited",                                                     "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("KAPCO",    "Kot Addu Power Company Limited",                                         "POWER GENERATION & DISTRIBUTION"),
    ("MACFL",    "MACPAC Films Limited",                                                   "PAPER, BOARD & PACKAGING"),
    ("INKL",     "International Knitwear Limited",                                         "TEXTILE COMPOSITE"),
    ("KOHC",     "Kohat Cement Company Limited",                                           "CEMENT"),
    ("HABSM",    "Habib Sugar Mills Limited",                                              "SUGAR & ALLIED INDUSTRIES"),
    ("MCB",      "MCB Bank Limited",                                                       "COMMERCIAL BANKS"),
    ("ICL",      "Ittehad Chemicals Limited",                                              "CHEMICAL"),
    ("SEARL",    "The Searle Company Limited",                                             "PHARMACEUTICALS"),
    ("SSML",     "Saritow Spinning Mills Limited",                                         "TEXTILE SPINNING"),
    ("AKGL",     "Al - Khair Gadoon Limited",                                              "MISCELLANEOUS"),
    ("IDYM",     "Indus Dyeing & Manufacturing Company Limited",                           "TEXTILE SPINNING"),
    ("IBLHL",    "IBL Healthcare Limited",                                                 "PHARMACEUTICALS"),
    ("DYNO",     "Dynea Pakistan Limited",                                                 "CHEMICAL"),
    ("SNAI",     "Sana Industries Limited",                                                "TEXTILE SPINNING"),
    ("SAIF",     "Saif Textile Mills Limited",                                             "TEXTILE SPINNING"),
    ("JVDC",     "Javedan Corporation Limited",                                            "PROPERTY"),
    ("CSAP",     "Crescent Steel & Allied Products Limited",                               "ENGINEERING"),
    ("EPCL",     "Engro Polymer & Chemicals Limited",                                      "CHEMICAL"),
    ("ATLH",     "Atlas Honda Limited",                                                    "AUTOMOBILE ASSEMBLER"),
    ("KPUS",     "Khairpur Sugar Mills Limited",                                           "SUGAR & ALLIED INDUSTRIES"),
    ("FFC",      "Fauji Fertilizer Company Limited",                                       "FERTILIZER"),
    ("ADAMS",    "Adam Sugar Mills Limited",                                               "SUGAR & ALLIED INDUSTRIES"),
    ("PSYL",     "Pakistan Synthetics Limited",                                            "SYNTHETIC & RAYON"),
    ("FTSM",     "First Tri - Star Modaraba",                                              "MODARABAS"),
    ("PTC",      "Pakistan Telecommunication Company Ltd.",                                "TECHNOLOGY & COMMUNICATION"),
    ("CPPL",     "Cherat Packaging Limited",                                               "PAPER, BOARD & PACKAGING"),
    ("NAGC",     "Nagina Cotton Mills Limited",                                            "TEXTILE SPINNING"),
    ("HALEON",   "Haleon Pakistan Limited (GlaxoSmithKline Consumer HealthCare)",          "PHARMACEUTICALS"),
    ("INIL",     "International Industries Limited",                                       "ENGINEERING"),
    ("ADMM",     "Artistic Denim Mills Limited",                                           "TEXTILE COMPOSITE"),
    ("TPLT",     "TPL Trakker Limited",                                                    "TECHNOLOGY & COMMUNICATION"),
    ("SBL",      "Samba Bank Limited",                                                     "COMMERCIAL BANKS"),
    ("BNWM",     "Bannu Woollen Mills Limited",                                            "WOOLLEN"),
    ("AICL",     "Adamjee Insurance Company Limited",                                      "INSURANCE"),
    ("GOC",      "GOC (Pak) Limited",                                                      "MISCELLANEOUS"),
    ("NETSOL",   "NetSol Technologies Limited",                                            "TECHNOLOGY & COMMUNICATION"),
    ("DCR",      "Dolmen City REIT",                                                       "REAL ESTATE INVESTMENT TRUST"),
    ("IGIL",     "IGI Life Insurance Limited",                                             "INSURANCE"),
    ("DNCC",     "Dandot Cement Company Limited",                                          "CEMENT"),
    ("PSO",      "Pakistan State Oil Company Limited",                                     "OIL & GAS MARKETING COMPANIES"),
    ("NATF",     "National Foods Limited",                                                 "FOOD & PERSONAL CARE PRODUCTS"),
    ("NCL",      "Nishat (Chunian) Limited",                                               "TEXTILE COMPOSITE"),
    ("NRSL",     "Nimir Resins Limited",                                                   "CHEMICAL"),
    ("LOTCHEM",  "Lotte Chemical Pakistan Limited",                                        "CHEMICAL"),
    ("GVGL",     "Ghani Value Glass Limited",                                              "GLASS & CERAMICS"),
    ("LIVENR",   "Liven Pharma Limited",                                                   "nan"),
    ("IPAK",     "International Packaging Films Limited",                                  "PAPER, BOARD & PACKAGING"),
    ("ELSM",     "Ellcot Spinning Mills Limited",                                          "TEXTILE SPINNING"),
    ("CEPB",     "Century Paper & Board Mills Limited",                                    "PAPER, BOARD & PACKAGING"),
    ("RPL",      "Roshan Packages Limited",                                                "PAPER, BOARD & PACKAGING"),
    ("TSPL",     "Tri - Star Power Limited",                                               "POWER GENERATION & DISTRIBUTION"),
    ("AGP",      "AGP Limited",                                                            "PHARMACEUTICALS"),
    ("EPQL",     "Engro Powergen Qadirpur Limited",                                        "POWER GENERATION & DISTRIBUTION"),
    ("PSX",      "Pakistan Stock Exchange Limited",                                        "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("SGF",      "Service Global Footwear Limited",                                        "LEATHER & TANNERIES"),
    ("FCL",      "Fast Cables Limited",                                                    "CABLE & ELECTRICAL GOODS"),
    ("FCCL",     "Fauji Cement Company Limited",                                           "CEMENT"),
    ("PTL",      "Panther Tyres Limited",                                                  "AUTOMOBILE PARTS & ACCESSORIES"),
    ("NEXT",     "Next Capital Limited",                                                   "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("FCEPL",    "Frieslandcampina Engro Pakistan Limited",                                "FOOD & PERSONAL CARE PRODUCTS"),
    ("AGTL",     "Al-Ghazi Tractors Limited",                                              "AUTOMOBILE ASSEMBLER"),
    ("UDLI",     "UDL International Limited",                                              "MISCELLANEOUS"),
    ("TPLI",     "TPL Insurance Limited",                                                  "INSURANCE"),
    ("OBOY",     "Oilboy Energy Limited  (Drekkar Kingsway Limited)",                      "OIL & GAS MARKETING COMPANIES"),
    ("SPWL",     "Saif Power Limited",                                                     "POWER GENERATION & DISTRIBUTION"),
    ("PMRS",     "The Premier Sugar Mills & Distillery Company Limited",                   "SUGAR & ALLIED INDUSTRIES"),
    ("LIVEN",    "Liven Pharma Limited (Landmark Spinning Industries Limited)",            "PHARMACEUTICALS"),
    ("JSGBETF",  "JS Global Banking Sector(ETF)",                                          "EXCHANGE TRADED FUNDS"),
    ("EFUL",     "EFU Life Assurance Limited",                                             "INSURANCE"),
    ("BAHL",     "Bank AL Habib  Limited",                                                 "COMMERCIAL BANKS"),
    ("PIBTL",    "Pakistan International Bulk Terminal Limited",                           "TRANSPORT"),
    ("TPLP",     "TPL Properties Limited",                                                 "PROPERTY"),
    ("LSEFSL",   "LSE Financial Services Limited",                                         "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ARCTM",    "Arctic Textile Mills Limited ",                                          "TEXTILE SPINNING"),
    ("PPVC",     "Pakistan PVC Limited",                                                   "CHEMICAL"),
    ("DSIL",     "D. S. Industries Limited",                                               "TEXTILE SPINNING"),
    ("KTML",     "Kohinoor Textile Mills Limited",                                         "TEXTILE COMPOSITE"),
    ("HAEL",     "Hala Enterprises Limited",                                               "TEXTILE COMPOSITE"),
    ("IMAGE",    "Image Pakistan Limited",                                                 "SYNTHETIC & RAYON"),
    ("GHGL",     "Ghani Glass Limited",                                                    "GLASS & CERAMICS"),
    ("SPEL",     "Synthetic Products Enterprises Limited",                                 "PAPER, BOARD & PACKAGING"),
    ("GATM",     "Gul Ahmed Textile Mills Limited",                                        "TEXTILE COMPOSITE"),
    ("BIPL",     "BankIslami Pakistan Limited",                                            "COMMERCIAL BANKS"),
    ("DOL",      "Descon Oxychem Limited",                                                 "CHEMICAL"),
    ("ORM",      "Orient Rental Modaraba",                                                 "MODARABAS"),
    ("ASTL",     "Amreli Steels Limited",                                                  "ENGINEERING"),
    ("OLPL",     "OLP Financial Services Pakistan Limited  (Orix Leasing Pakistan)",       "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("EXIDE",    "Exide Pakistan Limited",                                                 "AUTOMOBILE PARTS & ACCESSORIES"),
    ("GTYR",     "Ghandhara Tyre & Rubber Company Limited",                                "AUTOMOBILE PARTS & ACCESSORIES"),
    ("PIM",      "Popular Islamic Modaraba",                                               "MODARABAS"),
    ("SZTM",     "Shahzad Textile Mills Limited",                                          "TEXTILE SPINNING"),
    ("BERG",     "Berger Paints Pakistan Limited",                                         "CHEMICAL"),
    ("TCORP",    "Tariq Corporation Limited  (Husein Sugar Mills Limited)",                "SUGAR & ALLIED INDUSTRIES"),
    ("PICT",     "Pakistan International Container Terminal Ltd.",                         "TRANSPORT"),
    ("AKDSL",    "AKD Securities Limited ",                                                "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ACPL",     "Attock Cement Pakistan Limited",                                         "CEMENT"),
    ("CHBL",     "Chenab Limited",                                                         "TEXTILE COMPOSITE"),
    ("AVN",      "Avanceon Limited",                                                       "TECHNOLOGY & COMMUNICATION"),
    ("JSCL",     "Jahangir Siddiqui & Co. Limited",                                        "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("MFL",      "Matco Foods Limited",                                                    "FOOD & PERSONAL CARE PRODUCTS"),
    ("DWTM",     "Dewan Textile Mills Limited",                                            "TEXTILE SPINNING"),
    ("PIL",      "PICIC Insurance Limited",                                                "INSURANCE"),
    ("JSIL",     "JS Investments Limited",                                                 "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ALTN",     "Altern Energy Limited",                                                  "POWER GENERATION & DISTRIBUTION"),
    ("JATM",     "J. A. Textile Mills Limited",                                            "TEXTILE SPINNING"),
    ("AKBL",     "Askari Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("CRTM",     "The Crescent Textile Mills Limited",                                     "TEXTILE COMPOSITE"),
    ("DBCI",     "Dadabhoy Cement Industries Limited",                                     "CEMENT"),
    ("CPHL",     "Citi Pharma Limited",                                                    "PHARMACEUTICALS"),
    ("FPJM",     "First Punjab Modaraba",                                                  "MODARABAS"),
    ("PAEL",     "Pak Elektron Limited",                                                   "CABLE & ELECTRICAL GOODS"),
    ("IDRT",     "Idrees Textile Mills Limited",                                           "TEXTILE SPINNING"),
    ("FFL",      "Fauji Foods Limited",                                                    "FOOD & PERSONAL CARE PRODUCTS"),
    ("OLPM",     "OLP Modaraba",                                                           "MODARABAS"),
    ("ITTEFAQ",  "Ittefaq Iron Industries Limitd",                                         "ENGINEERING"),
    ("BFMOD",    "B. F. Modaraba",                                                         "MODARABAS"),
    ("UBLPETF",  "UBLPakistan Enterprise ETF",                                             "EXCHANGE TRADED FUNDS"),
    ("IBFL",     "Ibrahim Fibres Limited",                                                 "SYNTHETIC & RAYON"),
    ("CASH",     "CALCORP Limited ",                                                       "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("HASCOL",   "Hascol Petroleum Limited",                                               "OIL & GAS MARKETING COMPANIES"),
    ("NITGETF",  "NIT Pakistan Gateway ETF",                                               "EXCHANGE TRADED FUNDS"),
    ("MSCL",     "Metropolitan Steel Corporation Limited",                                 "ENGINEERING"),
    ("UBDL",     "United Brands Limited",                                                  "MISCELLANEOUS"),
    ("ACIETF",   "Alfalah Consumer Index (ETF)",                                           "EXCHANGE TRADED FUNDS"),
    ("POML",     "Punjab Oil Mills Limited",                                               "VANASPATI & ALLIED INDUSTRIES"),
    ("UVIC",     "The Universal Insurance Company Limited",                                "INSURANCE"),
    ("CYAN",     "Cyan Limited",                                                           "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("KML",      "Kohinoor Mills Limited",                                                 "TEXTILE COMPOSITE"),
    ("STJT",     "Shahtaj Textile Limited",                                                "TEXTILE WEAVING"),
    ("BRRG",     "B.R.R. Guardian Limited",                                                "PROPERTY"),
    ("JUBS",     "Jubilee Spinning & Weaving Mills Limited",                               "TEXTILE COMPOSITE"),
    ("BOK",      "The Bank of Khyber",                                                     "COMMERCIAL BANKS"),
    ("EPCLPS",   "Engro Polymer & Chemicals Limited (Preference Shares)",                  "CHEMICAL"),
    ("TSMF",     "Tri - Star Mutual Fund Limited",                                         "CLOSE - END MUTUAL FUND"),
    ("DFSM",     "Dewan Farooque Spinning Mills Limited",                                  "TEXTILE SPINNING"),
    ("SYM",      "Symmetry Group Limited",                                                 "TECHNOLOGY & COMMUNICATION"),
    ("PAKRI",    "Pakistan Reinsurance Company Limited",                                   "INSURANCE"),
    ("SLYT",     "Sally Textile Mills Limited",                                            "TEXTILE SPINNING"),
    ("AGSML",    "Abdullah Shah Ghazi Sugar Mills Limited",                                "SUGAR & ALLIED INDUSTRIES"),
    ("MQTM",     "Maqbool Textile Mills Limited",                                          "TEXTILE SPINNING"),
    ("ASHT",     "Ashfaq Textile Mills Limited",                                           "TEXTILE WEAVING"),
    ("BGL",      "Balochistan Glass Limited",                                              "GLASS & CERAMICS"),
    ("STPL",     "Siddiqsons Tin Plate Limited",                                           "MISCELLANEOUS"),
    ("OGDC",     "Oil & Gas Development Company Limited",                                  "OIL & GAS EXPLORATION COMPANIES"),
    ("BAFL",     "Bank Alfalah Limited",                                                   "COMMERCIAL BANKS"),
    ("FML",      "Feroze1888 Mills Limited ",                                              "TEXTILE COMPOSITE"),
    ("TBL",      "Treet Battery Limited",                                                  "AUTOMOBILE PARTS & ACCESSORIES"),
    ("HGFA",     "HBL Growth Fund ",                                                       "CLOSE - END MUTUAL FUND"),
    ("PKGI",     "The Pakistan General Insurance Company Limited",                         "INSURANCE"),
    ("HBLTETF",  "HBL Total Treasury ETF",                                                 "EXCHANGE TRADED FUNDS"),
    ("MZNPETF",  "Meezan Pakistan ETF",                                                    "EXCHANGE TRADED FUNDS"),
    ("786",      "786 Investments Limited",                                                "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("UCAPM",    "Unicap Modaraba",                                                        "MODARABAS"),
    ("MERIT",    "Merit Packaging Limited",                                                "PAPER, BOARD & PACKAGING"),
    ("JGICL",    "Jubilee General Insurance Company Limited",                              "INSURANCE"),
    ("SEPL",     "Security Papers Limited",                                                "PAPER, BOARD & PACKAGING"),
    ("GCWL",     "Ghani Chemworld Limited",                                                "CHEMICAL"),
    ("GFIL",     "Ghazi Fabrics International Limited",                                    "TEXTILE COMPOSITE"),
    ("ALAC",     "Askari Life Assurance Company Limited",                                  "INSURANCE"),
    ("AHCL",     "Arif Habib Corporation Limited",                                         "FERTILIZER"),
    ("TELE",     "Telecard Limited",                                                       "TECHNOLOGY & COMMUNICATION"),
    ("PINL",     "Premier Insurance Limited",                                              "INSURANCE"),
    ("MIIETF",   "Mahaana Islamic Index ETF",                                              "EXCHANGE TRADED FUNDS"),
    ("ANL",      "Azgard Nine Limited",                                                    "TEXTILE COMPOSITE"),
    ("SNBL",     "Soneri Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("YOUW",     "Yousaf Weaving Mills Limited",                                           "TEXTILE WEAVING"),
    ("ASTM",     "Asim Textile Mills Limited",                                             "TEXTILE SPINNING"),
    ("NBPGETF",  "NBP Pakistan Growth ETF",                                                "EXCHANGE TRADED FUNDS"),
    ("KCL",      "Karam Ceramics Limited",                                                 "GLASS & CERAMICS"),
    ("KEL",      "K-Electric Limited",                                                     "POWER GENERATION & DISTRIBUTION"),
    ("ASL",      "Aisha Steel Mills Limited",                                              "ENGINEERING"),
    ("CLCPS",    "Chenab Limited (Pref)",                                                  "TEXTILE COMPOSITE"),
    ("FANM",     "First Al - Noor Modaraba",                                               "MODARABAS"),
    ("DEL",      "Dawood Equities Limited",                                                "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("DCL",      "Dewan Cement Limited",                                                   "CEMENT"),
    ("DWSM",     "Dewan Sugar Mills Limited",                                              "SUGAR & ALLIED INDUSTRIES"),
    ("JSMFETF",  "JS Momentum Factor Exchange Traded Fund",                                "EXCHANGE TRADED FUNDS"),
    ("SLGL",     "Secure Logistics Group Limited",                                         "TRANSPORT"),
    ("AMBL",     "Apna Microfinance Bank Limited",                                         "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("SHCM",     "Shadman Cotton Mills Limited",                                           "TEXTILE SPINNING"),
    ("SIBL",     "Security Investment Bank Limited",                                       "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("PCAL",     "Pakistan Cables Limited",                                                "CABLE & ELECTRICAL GOODS"),
    ("HWQS",     "Haseeb Waqas Sugar Mills Limited",                                       "SUGAR & ALLIED INDUSTRIES"),
    ("CLVL",     "Cordoba Logistics & Ventures Limited",                                   "TRANSPORT"),
    ("LOADS",    "Loads Limited",                                                          "AUTOMOBILE PARTS & ACCESSORIES"),
    ("BUXL",     "Buxly Paints Limited",                                                   "CHEMICAL"),
    ("AGHA",     "Agha Steel Industries Limited",                                          "ENGINEERING"),
    ("OCTOPUS",  "Octopus Digital Limited",                                                "TECHNOLOGY & COMMUNICATION"),
    ("JSCLPSA",  "Jahangir Siddiqui & Co. Limited (Preference Shares)",                    "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("CTM",      "Colony Textile Mills Limited",                                           "TEXTILE SPINNING"),
    ("WAVES",    "Waves Corporation Limited ",                                             "CABLE & ELECTRICAL GOODS"),
    ("SNGP",     "Sui Northern Gas Pipelines Limited",                                     "OIL & GAS MARKETING COMPANIES"),
    ("TCORPCPS", "Tariq Corporation Limited(Pref)",                                        "SUGAR & ALLIED INDUSTRIES"),
    ("GGGL",     "Ghani Global Glass Limited",                                             "GLASS & CERAMICS"),
    ("DSL",      "Dost Steels Limited",                                                    "ENGINEERING"),
    ("TPLRF1",   "TPL REIT Fund - I",                                                      "REAL ESTATE INVESTMENT TRUST"),
    ("CNERGY",   "Cnergyico PK Limited  (Byco Petroleum Limited)",                         "REFINERY"),
    ("JSBL",     "JS Bank Limited",                                                        "COMMERCIAL BANKS"),
    ("STML",     "Shams Textile Mills Limited",                                            "TEXTILE COMPOSITE"),
    ("DADX",     "Dadex Eternit Limited",                                                  "ENGINEERING"),
    ("KOHP",     "Kohinoor Power Company Limited",                                         "POWER GENERATION & DISTRIBUTION"),
    ("PACE",     "Pace (Pakistan) Limited",                                                "PROPERTY"),
    ("BOP",      "The Bank of Punjab",                                                     "COMMERCIAL BANKS"),
    ("FCSC",     "First Capital Securities Corporation Limited",                           "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("CSIL",     "Crescent Star Insurance Company Limited",                                "INSURANCE"),
    ("NPL",      "Nishat Power Limited",                                                   "POWER GENERATION & DISTRIBUTION"),
    ("BILF",     "Bilal Fibres Limited",                                                   "TEXTILE SPINNING"),
    ("MDTL",     "Media Times Limited",                                                    "TECHNOLOGY & COMMUNICATION"),
    ("POWER",    "Power Cement Limited",                                                   "CEMENT"),
    ("BML",      "Bank Makramah Limited",                                                  "COMMERCIAL BANKS"),
    ("GRYL",     "Grays Leasing Limited",                                                  "LEASING COMPANIES"),
    ("PASL",     "Pervez Ahmed Consultancy Services Limited",                              "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("PMPK",     "Philip Morris (Pakistan) Limited",                                       "TOBACCO"),
    ("TSML",     "Tandlianwala Sugar Mills Limited",                                       "SUGAR & ALLIED INDUSTRIES"),
    ("ARPAK",    "Arpak International Investments Ltd.",                                   "MISCELLANEOUS"),
    ("ALIFE",    "Adamjee Life Assurance Company Limited",                                 "INSURANCE"),
    ("BIFO",     "Biafo Industries Limited",                                               "CHEMICAL"),
    ("ASLPS",    "Aisha Steel Convertible (Pref)",                                         "ENGINEERING"),
    ("HICL",     "Habib Insurance Company Limited",                                        "INSURANCE"),
    ("DMTM",     "Dewan Mushtaq Textile Mills Limited",                                    "TEXTILE SPINNING"),
    ("BECO",     "Beco Steel Limited",                                                     "ENGINEERING"),
    ("EWIC",     "East West Insurance Company Limited",                                    "INSURANCE"),
    ("IREIT",    "Image Reit",                                                             "nan"),
    ("JVDCPS",   "Javedan Corporation (Pref)",                                             "PROPERTY"),
    ("GIL",      "Good Luck Industries Ltd.",                                              "FOOD & PERSONAL CARE PRODUCTS"),
    ("AWTX",     "Allawasaya Tex. & Finishing Mills Ltd",                                  "TEXTILE SPINNING"),
    ("ANLNV",    "Azgard Nine Non-Voting Ordinary Shares",                                 "TEXTILE COMPOSITE"),
    ("FCONM",    "First Constellation Modaraba",                                           "MODARABAS"),
    ("SLCPA",    "Security Leasing Corp.9.10%(Pref)",                                      "LEASING COMPANIES"),
    ("NATM",     "Nadeem Textile Mills Limited",                                           "TEXTILE SPINNING"),
    ("MSOTPS",   "Masood Textile (Pref)",                                                  "TEXTILE COMPOSITE"),
    ("ANLPS",    "Azgard Nine 8.95%(Pref)",                                                "TEXTILE COMPOSITE"),
    ("KOSM",     "Kohinoor Spinning Mills Limited",                                        "TEXTILE SPINNING"),
    ("ZTL",      "Zephyr Textiles Limited",                                                "TEXTILE WEAVING"),
    ("WTL",      "WorldCall Telecom Limited",                                              "TECHNOLOGY & COMMUNICATION"),
    ("AGIC",     "Askari General Insurance Company Limited",                               "INSURANCE"),
    ("FECTC",    "Fecto Cement Limited",                                                   "CEMENT"),
    ("HIFA",     "HBL Investment Fund",                                                    "CLOSE - END MUTUAL FUND"),
    ("WAVESAPP", "Waves Home Appliances Limited ",                                         "CABLE & ELECTRICAL GOODS"),
    ("ZAHID",    "Zahidjee Textile Mills Limited",                                         "TEXTILE COMPOSITE"),
    ("STCL",     "Shabbir Tiles & Ceramics Limited",                                       "GLASS & CERAMICS"),
    ("WASL",     "Wasl Mobility Modaraba",                                                 "MODARABAS"),
    ("AMTEX",    "Amtex Limited",                                                          "TEXTILE SPINNING"),
    ("HIRAT",    "Hira Textile Mills Limited",                                             "TEXTILE SPINNING"),
    ("KOHE",     "Kohinoor Energy Limited",                                                "POWER GENERATION & DISTRIBUTION"),
    ("AHTM",     "Ahmad Hassan Textile Mills Limited",                                     "TEXTILE COMPOSITE"),
    ("PREMA",    "At-Tahur Limited",                                                       "FOOD & PERSONAL CARE PRODUCTS"),
    ("TPL",      "TPL Corp. Limited",                                                      "TECHNOLOGY & COMMUNICATION"),
    ("UNIC",     "The United Insurance Company of Pakistan Limited",                       "INSURANCE"),
    ("GRR",      "Globe Residency REIT",                                                   "REAL ESTATE INVESTMENT TRUST"),
    ("FABL",     "Faysal Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("FCEL",     "First Capital Equities Limited",                                         "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ICCI",     "ICC Industries Limited",                                                 "TEXTILE WEAVING"),
    ("BAPL",     "Bawany Air Products Limited",                                            "CHEMICAL"),
    ("POWERPS",  "Power Cement Limited  (Preference Shares)",                              "CEMENT"),
    ("ICIBL",    "Invest Capital Investment Bank Limited",                                 "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("GUSM",     "Gulistan Spinning Mills Limited",                                        "TEXTILE SPINNING"),
    ("UNITY",    "Unity Foods Limited",                                                    "FOOD & PERSONAL CARE PRODUCTS"),
    ("HRPL",     "Habib Rice Products Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("FIBLM",    "First IBL Modaraba",                                                     "MODARABAS"),
    ("NCML",     "Nazir Cotton Mills Limited",                                             "TEXTILE SPINNING"),
    ("SHNI",     "Shaheen Insurance Company Limited",                                      "INSURANCE"),
    ("RUBY",     "Ruby Textile Mills Limited",                                             "TEXTILE SPINNING"),
    ("FFLM",     "First Fidelity Leasing Modaraba",                                        "MODARABAS"),
    ("GAMON",    "Gammon Pakistan Limited",                                                "MISCELLANEOUS"),
    ("FDPL",     "First Dawood Properties Limited (First Dawood Investment Bank)",         "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("IMS",      "Intermarket Securities Limited (EFG Hermes Pakistan Limited)",           "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("RCML",     "Reliance Cotton Spinning Mills Limited",                                 "TEXTILE SPINNING"),
    ("PGLC",     "Pak-Gulf Leasing Company Limited",                                       "LEASING COMPANIES"),
    ("GGL",      "Ghani Global Holdings Limited ",                                         "CHEMICAL"),
    ("TREET",    "Treet Corporation Limited",                                              "FOOD & PERSONAL CARE PRODUCTS"),
    ("MTL",      "Millat Tractors Limited",                                                "AUTOMOBILE ASSEMBLER"),
    ("TOMCL",    "The Organic Meat Company Limited",                                       "FOOD & PERSONAL CARE PRODUCTS"),
    ("ANSM",     "Ansari Sugar Mills Limited",                                             "SUGAR & ALLIED INDUSTRIES"),
    ("FTMM",     "First Treet Manufacturing Modaraba",                                     "MODARABAS"),
    ("ASIC",     "Asia Insurance Company Limited",                                         "INSURANCE"),
    ("SANSM",    "Sanghar Sugar Mills Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("CLOV",     "Clover Pakistan Limited",                                                "FOOD & PERSONAL CARE PRODUCTS"),
    ("QUET",     "Quetta Textile Mills Limited",                                           "TEXTILE COMPOSITE"),
    ("PRL",      "Pakistan Refinery Limited",                                              "REFINERY"),
    ("ASC",      "Al Shaheer Corporation Limited",                                         "FOOD & PERSONAL CARE PRODUCTS"),
    ("FNEL",     "First National Equities Limited",                                        "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("FHAM",     "First Habib Modaraba ",                                                  "MODARABAS"),
    ("PABC",     "Pakistan Aluminium Beverage Cans Limited",                               "MISCELLANEOUS"),
    ("LPL",      "Lalpir Power Limited",                                                   "POWER GENERATION & DISTRIBUTION"),
    ("TRG",      "TRG Pakistan Limited",                                                   "TECHNOLOGY & COMMUNICATION"),
    ("RICL",     "Reliance Insurance Company Limited",                                     "INSURANCE"),
    ("GSPM",     "Gulshan Spinning Mills Limited",                                         "TEXTILE SPINNING"),
    ("HTL",      "Hi-Tech Lubricants Limited",                                             "OIL & GAS MARKETING COMPANIES"),
    ("DIIL",     "Diamond Industries Limited",                                             "MISCELLANEOUS"),
    ("ILP",      "Interloop Limited",                                                      "TEXTILE COMPOSITE"),
    ("HCAR",     "Honda Atlas Cars (Pakistan) Limited",                                    "AUTOMOBILE ASSEMBLER"),
    ("SHEZ",     "Shezan International Limited",                                           "FOOD & PERSONAL CARE PRODUCTS"),
    ("DWAE",     "Dewan Automotive Engineering Limited",                                   "AUTOMOBILE PARTS & ACCESSORIES"),
    ("SURC",     "Suraj Cotton Mills Limited",                                             "TEXTILE COMPOSITE"),
    ("CCM",      "Crescent Cotton Mills Limited",                                          "TEXTILE SPINNING"),
    ("FPRM",     "First Paramount Modaraba",                                               "MODARABAS"),
    ("HUSI",     "Husein Industries Limited",                                              "PROPERTY"),
    ("SMCPL",    "Safe Mix Concrete Limited",                                              "CEMENT"),
    ("BPL",      "Burshane LPG (Pakistan) Limited",                                        "OIL & GAS MARKETING COMPANIES"),
    ("AATM",     "Ali Asghar Textile Mills Limited",                                       "TEXTILE SPINNING"),
    ("BFAGRO",   "Barkat Frisian Agro Limited",                                            "FOOD & PERSONAL CARE PRODUCTS"),
    ("ARUJ",     "Aruj Industries Limited",                                                "TEXTILE COMPOSITE"),
    ("FRSM",     "Faran Sugar Mills Limited",                                              "SUGAR & ALLIED INDUSTRIES"),
    ("LSEVL",    "LSE Ventures Limited",                                                   "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("IDSM",     "Ideal Spinning Mills Limited",                                           "TEXTILE SPINNING"),
    ("DFML",     "Dewan Farooque Motors Limited",                                          "AUTOMOBILE ASSEMBLER"),
    ("BFBIO",    "BF Biosciences Limited",                                                 "PHARMACEUTICALS"),
    ("REDCO",    "Redco Textiles Limited",                                                 "TEXTILE COMPOSITE"),
    ("ATBA",     "Atlas Battery Limited",                                                  "AUTOMOBILE PARTS & ACCESSORIES"),
    ("STYLERS",  "Stylers International Limited",                                          "TEXTILE COMPOSITE"),
    ("IML",      "Imperial Limited (Imperial Sugar)",                                      "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("GCIL",     "Ghani Chemical Industries Limited",                                      "CHEMICAL"),
    ("DINT",     "Din Textile Mills Limited",                                              "TEXTILE SPINNING"),
    ("SERT",     "Service Industries Textiles Limited",                                    "TEXTILE SPINNING"),
    ("PASM",     "Paramount Spinning Mills Limited",                                       "TEXTILE COMPOSITE"),
    ("NICL",     "Nimir Industrial Chemicals Limited",                                     "CHEMICAL"),
    ("ESBL",     "Escorts Investmen Bank Limited",                                         "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("HUMNL",    "Hum Network Limited",                                                    "TECHNOLOGY & COMMUNICATION"),
    ("IGIHL",    "IGI Holdings Limited",                                                   "INSURANCE"),
    ("ECOP",     "EcoPack Limited",                                                        "MISCELLANEOUS"),
    ("SHDT",     "Shadab Textile Mills Limited",                                           "TEXTILE SPINNING"),
    ("DAAG",     "Data Agro Limited",                                                      "CHEMICAL"),
    ("MIRKS",    "Mirpurkhas Sugar Mills Limited",                                         "SUGAR & ALLIED INDUSTRIES"),
    ("ABL",      "Allied Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("APL",      "Attock Petroleum Limited",                                               "OIL & GAS MARKETING COMPANIES"),
    ("EFUG",     "EFU General Insurance Limited",                                          "INSURANCE"),
    ("NONS",     "Noon Sugar Mills Limited",                                               "SUGAR & ALLIED INDUSTRIES"),
    ("ALNRS",    "Al-Noor Sugar Mills Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("SCBPL",    "Standard Chartered Bank (Pakistan) Ltd.",                                "COMMERCIAL BANKS"),
    ("PKGS",     "Packages Limited",                                                       "PAPER, BOARD & PACKAGING"),
    ("BBFL",     "Big Bird Foods Limited",                                                 "FOOD & PERSONAL CARE PRODUCTS"),
    ("FECM",     "First Elite Capital Modaraba",                                           "MODARABAS"),
    ("FEM",      "First Equity Modaraba",                                                  "MODARABAS"),
    ("CHAS",     "Chashma Sugar Mills Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("KOHTM",    "Kohat Textile Mills Limited",                                            "TEXTILE SPINNING"),
    ("PAKOXY",   "Pakistan Oxygen Limited (Linde Pakistan Limited)",                       "CHEMICAL"),
    ("OML",      "Olympia Mills Limited",                                                  "MISCELLANEOUS"),
    ("TSBL",     "Trust Securities & Brokerage Limited",                                   "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("ZAL",      "Zarea Limited",                                                          "TECHNOLOGY & COMMUNICATION"),
    ("GWLC",     "Gharibwal Cement Limited",                                               "CEMENT"),
    ("PKGP",     "Pakgen Power Limited",                                                   "POWER GENERATION & DISTRIBUTION"),
    ("KOIL",     "Kohinoor Industries Limited",                                            "TEXTILE COMPOSITE"),
    ("ATIL",     "Atlas Insurance Limited",                                                "INSURANCE"),
    ("HMB",      "Habib Metropolitan Bank Limited",                                        "COMMERCIAL BANKS"),
    ("LEUL",     "Leather Up Limited",                                                     "LEATHER & TANNERIES"),
    ("JLICL",    "Jubilee Life Insurance Company Limited",                                 "INSURANCE"),
    ("SKRS",     "Sakrand Sugar Mills Limited",                                            "SUGAR & ALLIED INDUSTRIES"),
    ("FLYNG",    "Flying Cement Company Limited",                                          "CEMENT"),
    ("KSTM",     "Khalid Siraj Textile Mills Limited",                                     "TEXTILE SPINNING"),
    ("MSOT",     "Masood Textile Mills Limited",                                           "TEXTILE COMPOSITE"),
    ("SSGC",     "Sui Southern Gas Company Limited",                                       "OIL & GAS MARKETING COMPANIES"),
    ("MRNS",     "Mehran Sugar Mills Limited",                                             "SUGAR & ALLIED INDUSTRIES"),
    ("RUPL",     "Rupali Polyester Limited",                                               "SYNTHETIC & RAYON"),
    ("ANTM",     "AN Textile Mills Limited",                                               "TEXTILE COMPOSITE"),
    ("PRWM",     "Prosperity Weaving Mills Limited",                                       "TEXTILE WEAVING"),
    ("MACTER",   "Macter International Limited",                                           "PHARMACEUTICALS"),
    ("MARI",     "Mari Petroleum Company Limited",                                         "OIL & GAS EXPLORATION COMPANIES"),
    ("TPLL",     "TPL Life Insurance Limited  (Dar Es Salaam Textile Mills Limited)",      "INSURANCE"),
    ("EFERT",    "Engro Fertilizers Limited",                                              "FERTILIZER"),
    ("CJPL",     "Crescent Jute Products Limited",                                         "JUTE"),
    ("CENI",     "Century Insurance Company Limited",                                      "INSURANCE"),
    ("PAKD",     "Pak Datacom Limited",                                                    "TECHNOLOGY & COMMUNICATION"),
    ("LSECL",    "LSE Capital Limited",                                                    "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("THCCL",    "Thatta Cement Company Limited",                                          "CEMENT"),
    ("AGL",      "Agritech Limited",                                                       "FERTILIZER"),
    ("WAHN",     "Wah Noble Chemicals Limited",                                            "CHEMICAL"),
    ("MFFL",     "Mitchell's Fruit Farms Limited",                                         "FOOD & PERSONAL CARE PRODUCTS"),
    ("HUBC",     "The Hub Power Company Limited",                                          "POWER GENERATION & DISTRIBUTION"),
    ("OTSU",     "Otsuka Pakistan Limited",                                                "PHARMACEUTICALS"),
    ("AIRLINK",  "Air Link Communication Limited",                                         "TECHNOLOGY & COMMUNICATION"),
    ("SARC",     "Sardar Chemical Industries Limited",                                     "CHEMICAL"),
    ("FRCL",     "Frontier Ceramics Limited",                                              "GLASS & CERAMICS"),
    ("MEBL",     "Meezan Bank Limited",                                                    "COMMERCIAL BANKS"),
    ("FSWL",     "Fateh Sports Wear Limited",                                              "TEXTILE COMPOSITE"),
    ("GAL",      "Ghandhara Automobiles Limited  (Ghandhara Nissan Limited)",              "AUTOMOBILE ASSEMBLER"),
    ("JKSM",     "J. K. Spinning Mills Limited",                                           "TEXTILE SPINNING"),
    ("MEHT",     "Mahmood Textile Mills Limited",                                          "TEXTILE COMPOSITE"),
    ("FATIMA",   "Fatima Fertilizer Company Limited",                                      "FERTILIZER"),
    ("FEROZ",    "Ferozsons Laboratories Limited",                                         "PHARMACEUTICALS"),
    ("SHFA",     "Shifa International Hospitals Limited",                                  "MISCELLANEOUS"),
    ("TATM",     "Tata Textile Mills Limited",                                             "TEXTILE SPINNING"),
    ("PAKT",     "Pakistan Tobacco Company Limited",                                       "TOBACCO"),
    ("CFL",      "Crescent Fibres Limited",                                                "TEXTILE SPINNING"),
    ("EMCO",     "Emco Industries Limited",                                                "CABLE & ELECTRICAL GOODS"),
    ("GLAXO",    "GlaxoSmithKline Pakistan Limited",                                       "PHARMACEUTICALS"),
    ("TRSM",     "Trust Modaraba",                                                         "MODARABAS"),
    ("LPGL",     "Leiner Pak Gelatine Limited",                                            "CHEMICAL"),
    ("PAKL",     "Pak Leather Crafts Limited",                                             "LEATHER & TANNERIES"),
    ("ATRL",     "Attock Refinery Limited",                                                "REFINERY"),
    ("KSBP",     "KSB Pumps Company Limited",                                              "ENGINEERING"),
    ("COLG",     "Colgate - Palmolive (Pakistan) Limited",                                 "FOOD & PERSONAL CARE PRODUCTS"),
    ("SSOM",     "S. S. Oil Mills Limited",                                                "VANASPATI & ALLIED INDUSTRIES"),
    ("POL",      "Pakistan Oilfields Limited",                                             "OIL & GAS EXPLORATION COMPANIES"),
    ("LCI",      "Lucky Core Industries Limited (ICI Pakistan Limited)",                   "CHEMICAL"),
    ("DHPL",     "DH Partners Limited",                                                    "INV. BANKS / INV. COS. / SECURITIES COS."),
    ("AABS",     "Al-Abbas Sugar Mills Limited",                                           "SUGAR & ALLIED INDUSTRIES"),
    ("HINO",     "Hinopak Motors Limited",                                                 "AUTOMOBILE ASSEMBLER"),
    ("KHYT",     "Khyber Textile Mills Limited",                                           "TEXTILE COMPOSITE"),
    ("BELA",     "Bela Automotives Limited",                                               "AUTOMOBILE PARTS & ACCESSORIES"),
    ("ASLCPS",   "Aisha Steel Convt (Pref) Right",                                         "ENGINEERING"),
    ("PNSC",     "Pakistan National Shipping Corporation",                                 "TRANSPORT"),
    ("PECO",     "Pakistan Engineering Company Limited",                                   "ENGINEERING"),
    ("GHNI",     "Ghandhara Industries Limited",                                           "AUTOMOBILE ASSEMBLER"),
    ("MUREB",    "Murree Brewery Company Limited",                                         "FOOD & PERSONAL CARE PRODUCTS"),
    ("BTL",      "Blessed Textiles Limited",                                               "TEXTILE COMPOSITE"),
    ("ARPL",     "Archroma Pakistan Limited",                                              "CHEMICAL"),
    ("MWMP",     "Mandviwalla Mauser Plastic Industries Limited",                          "MISCELLANEOUS"),
    ("TICL",     "The Thal Industries Corporation Limited",                                "SUGAR & ALLIED INDUSTRIES"),
    ("NESTLE",   "Nestle Pakistan Limited",                                                "FOOD & PERSONAL CARE PRODUCTS"),
    ("ELCM",     "Elahi Cotton Mills Limited",                                             "TEXTILE SPINNING"),
    ("SPL",      "Sitara Peroxide Limited",                                                "CHEMICAL"),
    ("KHTC",     "Khyber Tobacco Company Limited",                                         "TOBACCO"),
    ("REWM",     "Reliance Weaving Mills Limited",                                         "TEXTILE COMPOSITE"),
    ("ZIL",      "ZIL Limited",                                                            "FOOD & PERSONAL CARE PRODUCTS"),
    ("SIEM",     "Siemens (Pakistan) Engineering Co. Limited",                             "CABLE & ELECTRICAL GOODS"),
    ("BWCL",     "Bestway Cement Limited",                                                 "CEMENT"),
    ("SCL",      "Shield Corporation Limited",                                             "FOOD & PERSONAL CARE PRODUCTS"),
    ("STL",      "Supernet Technologies Limited",                                          "TECHNOLOGY & COMMUNICATION"),
    ("HINOON",   "Highnoon Laboratories Limited",                                          "PHARMACEUTICALS"),
    ("ISIL",     "Ismail Industries Limited",                                              "FOOD & PERSONAL CARE PRODUCTS"),
    ("SRVI",     "Service Industries Limited",                                             "LEATHER & TANNERIES"),
    ("INDU",     "Indus Motor Company Limited",                                            "AUTOMOBILE ASSEMBLER"),
    ("HPL",      "Hoechst Pakistan Limited (Sanofi-Aventis Pakistan Limited)",             "PHARMACEUTICALS"),
    ("SFL",      "Sapphire Fibres Limited",                                                "TEXTILE COMPOSITE"),
    ("BNL",      "Bunny's Limited",                                                        "FOOD & PERSONAL CARE PRODUCTS"),
    ("SAZEW",    "Sazgar Engineering Works Limited",                                       "AUTOMOBILE ASSEMBLER"),
    ("PSEL",     "Pakistan Services Limited",                                              "MISCELLANEOUS"),
    ("UPFL",     "Unilever Pakistan Foods Limited",                                        "FOOD & PERSONAL CARE PRODUCTS"),
    ("PIAHCLB",  "PIA Holding Company LimitedB",                                           "INV. BANKS / INV. COS. / SECURITIES COS."),
]